GET http://localhost:3000/products/3.json

###

POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "froot loop",
  "price": 5,
  "image_url": "url", 
  "description": "food"
}

###

PATCH http://localhost:3000/products/3.json
Content-Type: application/json

{
  "price": 12
}

###

DELETE http://localhost:3000/products/1.json

###

POST http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Hailey",
  "email": "juiwsgiw@example.com",
  "password": "Sike100",
  "password_confirmation": "Sike100"
}


###

POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzg4MTU3NDB9.VkLkRD6Xz_tttS7DkJFz5m4A3wDD5uI1c-Qi9llKYjc
Content-Type: application/json

{
 "user_id": 3,
 "product_id": 3,
 "quantity": 2,
 "subtotal": 30.00,
 "tax": 1.50,
 "total": 31.50
}

###

GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MTQ4Nzl9.qav4bC3zlr8h5_dLgUKYXwJIT1Vx4dS_Bz-pZde_pEE

###

GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2Nzg4MTU3NDB9.VkLkRD6Xz_tttS7DkJFz5m4A3wDD5uI1c-Qi9llKYjc